; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                                  = 10180924-x86_64 Linux               
[ DataSettings ]
datatype                             = snNucleotide                        
containsCodingNuc                    = False                               
MissingBaseSymbol                    = ?                                   
IdenticalBaseSymbol                  = .                                   
GapSymbol                            = -                                   
[ ProcessTypes ]
ppRelTimeML                          = true                                
[ AnalysisSettings ]
Analysis                             = Estimate Divergence Times (ML)      
Tree to Use                          = Use tree from file                  
Reltime Settings                     = ====================                
Clock Type                           = Local clocks                        
Variance Estimation Method           = Analytical method                   
Max Relative Rate Ratio              = 20                                  
Statistical Method                   = Maximum Likelihood                  
Substitution Model                   = ====================                
Substitutions Type                   = Nucleotide                          
Model/Method                         = Tamura-Nei model                    
Rates and Patterns                   = ====================                
Rates among Sites                    = Uniform Rates                       
No of Discrete Gamma Categories      = Not Applicable                      
Data Subset to Use                   = ====================                
Gaps/Missing Data Treatment          = Use all sites                       
Site Coverage Cutoff (%)             = Not Applicable                      
System Resource Usage                = ====================                
Number of Threads                    = 7                                   
Has Time Limit                       = False                               
Maximum Execution Time               = -1                                  
